import { useParams, Navigate } from 'react-router-dom';
import { useEffect } from 'react';

const legalContent = {
    'terms-of-service': {
        title: 'Terms of Service',
        content: `
      <p>Last updated: November 29, 2025</p>
      <h3>1. Agreement to Terms</h3>
      <p>By accessing our website, you agree to be bound by these Terms of Service and to comply with all applicable laws and regulations.</p>
      
      <h3>2. Use License</h3>
      <p>Permission is granted to temporarily download one copy of the materials (information or software) on ILovMe's website for personal, non-commercial transitory viewing only.</p>
      
      <h3>3. Disclaimer</h3>
      <p>The materials on ILovMe's website are provided on an 'as is' basis. ILovMe makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
      
      <h3>4. Limitations</h3>
      <p>In no event shall ILovMe or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on ILovMe's website.</p>
    `
    },
    'privacy-policy': {
        title: 'Privacy Policy',
        content: `
      <p>Last updated: November 29, 2025</p>
      <h3>1. Information We Collect</h3>
      <p>We collect information you provide directly to us, such as when you create an account, upload photos, or communicate with us.</p>
      
      <h3>2. How We Use Your Information</h3>
      <p>We use the information we collect to provide, maintain, and improve our services, including generating virtual try-on images.</p>
      
      <h3>3. Photo Data</h3>
      <p>Photos you upload are processed solely for the purpose of generating virtual try-on results. We do not use your photos for training public AI models without your explicit consent.</p>
      
      <h3>4. Data Security</h3>
      <p>We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction.</p>
    `
    },
    'refund-policy': {
        title: 'Refund Policy',
        content: `
      <p>Last updated: November 29, 2025</p>
      <h3>1. Subscription Refunds</h3>
      <p>If you are not satisfied with our service, you may request a refund within 14 days of your initial purchase, provided you have not used a significant portion of the service (e.g., generated a large number of images).</p>
      
      <h3>2. Processing</h3>
      <p>Refunds are processed to the original payment method. Please allow 5-10 business days for the refund to appear on your statement.</p>
      
      <h3>3. Contact Us</h3>
      <p>To request a refund, please contact our support team with your order details.</p>
    `
    },
    'acceptable-use-policy': {
        title: 'Acceptable Use Policy',
        content: `
      <p>Last updated: November 29, 2025</p>
      <h3>1. Prohibited Content</h3>
      <p>You may not use our service to generate, upload, or share content that:</p>
      <ul>
        <li>Is illegal, harmful, or promotes violence.</li>
        <li>Is sexually explicit or pornographic.</li>
        <li>Infringes on the intellectual property rights of others.</li>
        <li>Harasses, bullies, or intimidates others.</li>
      </ul>
      
      <h3>2. Account Suspension</h3>
      <p>We reserve the right to suspend or terminate accounts that violate this policy.</p>
    `
    },
    'ai-disclaimer': {
        title: 'AI Disclaimer',
        content: `
      <p>Last updated: November 29, 2025</p>
      <h3>1. Nature of AI Generation</h3>
      <p>The images generated by our service are created using artificial intelligence. While we strive for realism, the results are simulations and may not perfectly reflect real-world fit, fabric texture, or lighting.</p>
      
      <h3>2. No Guarantees</h3>
      <p>We do not guarantee that the virtual try-on results will be 100% accurate. Users should use their own judgment when making purchasing decisions based on these images.</p>
    `
    },
    'content-safety-policy': {
        title: 'Content Safety Policy',
        content: `
      <p>Last updated: November 29, 2025</p>
      <h3>1. Safety Measures</h3>
      <p>We employ automated and manual moderation tools to detect and prevent the generation of unsafe or inappropriate content.</p>
      
      <h3>2. Reporting</h3>
      <p>If you encounter any content generated by our service that you believe violates our safety policies, please report it to us immediately.</p>
      
      <h3>3. User Responsibility</h3>
      <p>Users are responsible for the photos they upload and the prompts they use. Attempting to bypass our safety filters is a violation of our Terms of Service.</p>
    `
    }
};

const Legal = () => {
    const { slug } = useParams();

    useEffect(() => {
        window.scrollTo(0, 0);
    }, [slug]);

    if (!slug || !legalContent[slug]) {
        return <Navigate to="/" replace />;
    }

    const { title, content } = legalContent[slug];

    return (
        <div className="min-h-screen bg-gray-50 pt-24 pb-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-100 p-8 sm:p-12">
                <h1 className="text-3xl font-serif font-bold text-gray-900 mb-8">{title}</h1>
                <div
                    className="prose prose-stone max-w-none"
                    dangerouslySetInnerHTML={{ __html: content }}
                />
            </div>
        </div>
    );
};

export default Legal;
